name: 14 - Using Cache.

on:
    workflow_dispatch:
        inputs:
            use-cache:
                description: 'Whether to execute cache step'
                type: boolean
                default: true
            node-version:
                description: Node version
                type: choice
                options:
                    - 18.x
                    - 20.x
                    - 21.x
                default: '20.x'

jobs:
    build:
        runs-on: ubuntu-latestÂ´
        # defaults:
        #     run:
        #         working-directory: my-app
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: ${{inputs.node-version}}
            - name: Download cached dependencies
              id: cache
              if: ${{inputs.use-cache}}
              uses: actions/cache@v3
              with:
                  path: ./node_modules
                  key: deps-node-modules-${{ hashFiles('./package-lock.json') }}
            - name: Install dependencies
              if: ${{steps.cache.outputs.cache-hit != 'true'}}
              run: npm ci
            - name: Testing
              run: npm run test
            - name: Building
              run: npm run build
            - name: Deploying to nonprod
              run: echo "Deploying to nonprod"
